name:                chat
version:             0.1.0.0
github:              "meowcolm024/chat"
license:             BSD3
author:              "Meowcolm024"
maintainer:          "luoyicong1026@live.com"
copyright:           "2022 Meowcolm024"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/meowcolm024/chat#readme>

dependencies:
- base >= 4.7 && < 5
- network >= 3 && < 4

library:
  source-dirs: src

executables:
  server:
    main:                Server.hs
    source-dirs:         app
    ghc-options:
    -  -main-is Server
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - chat

  client:
    main:                Client.hs
    source-dirs:         app
    ghc-options:
    - -main-is Client
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - chat
